name: GitHub Action

on:
  push:
    branches:
      - main

jobs:
  maven:
    runs-on: ubuntu-latest

    container:
      image: maven:latest
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Run Maven clean install
        run: mvn clean install